### ISSUE TITLE
Logo and Branding

### ISSUE THREAD

**Issue by Shivg2901** [Shivg2901/zapier-prototype#1]
Design a simple and appropriate logo and brand name for the application

**Comment by mayank-0789** [comment]
Hey @Shivg2901  please assign this issue to me

**Comment by Shivg2901** [comment]
@mayank-0789 
assigned

**Comment by Sushil010** [comment]
Hey @Shivg2901 can you assign this to me

**Comment by Kuldeepagrahari** [comment]
hello [Shivg2901](https://github.com/Shivg2901),
You can assign me this issue , I will use Canva and suitable properties of CSS too to make best looking logo for this application

**Comment by Shivg2901** [comment]
@Kuldeepagrahari Sure!
assigned

**Comment by Kuldeepagrahari** [comment]
Alright,
I'm suggesting you the brand names which i think will be suitable for application:
1.Triggo
2.Flownix
3.Synexium
4.Nexora

you select one I will embed that with the logo

**Comment by Shivg2901** [comment]
@Kuldeepagrahari 
I think Triggo is good

**Comment by Kuldeepagrahari** [comment]
Its Done. Please Merge this PR
![image](https://github.com/user-attachments/assets/5cc31969-7a9c-45b2-a6c3-363db31cc345)
