### ISSUE TITLE
Improve the UI/UX of the login page

### ISSUE THREAD

**Issue by KhushiParekh** [Shivg2901/zapier-prototype#18]
## 📝 Description
To improve the UI of the login page, I would like to add the following enhancements:
A toggle feature to show/hide the password for better user experience.
A toggle option to switch between the login and signup pages directly from the login page.
Correct the alignment of elements on the login page to ensure a more polished look.

### 📷 Screenshot or Visual Reference (optional)
<img width="1438" alt="Screenshot 2024-10-22 at 10 01 16 AM" src="https://github.com/user-attachments/assets/dac89511-01b4-4874-809d-a00199c6df01">

## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Open the login page.
  2. Add toggle for visibility and the login/signup 
  3. Improve the overall UI
  
- **Expected behavior:**The user should be able to toggle password visibility.A clear option to switch between the login and signup pages should be present.
- **Actual behavior:** No password visibility toggle is present.

## 💡 Enhancement / Feature Request (if applicable)
Adding a password visibility toggle will make it easier for users to avoid input errors. A toggle between the login and signup pages will streamline navigation, and correcting the alignment will ensure a more user-friendly interface.

**Comment by Shivg2901** [comment]
@KhushiParekh 
I have assigned it to you
Kindly attach screenshot on opening a pull request

**Comment by KhushiParekh** [comment]
<img width="1436" alt="Screenshot 2024-10-22 at 4 00 19 PM" src="https://github.com/user-attachments/assets/7d017ca1-1d54-49ed-b6fb-1b195dac9b76">
<img width="1437" alt="Screenshot 2024-10-22 at 4 00 35 PM" src="https://github.com/user-attachments/assets/18037139-e10c-45a2-84d7-7b0e286d301d">

**Comment by Shivg2901** [comment]
@KhushiParekh open pr
