### ISSUE TITLE
 Potential Issue Due to Missing Try-Catch Blocks in API Routes

### ISSUE THREAD

**Issue by mesalm** [Shivg2901/zapier-prototype#19]
I have identified a potential issue in the user authentication routes (/signin, /signup, etc.) due to the absence of try-catch blocks around asynchronous operations, such as database queries and JWT signing.
Problem

Currently, the API routes for user signup and signin do not handle errors from asynchronous operations like database calls (prismaClient.user.findFirst()) or JWT signing (jwt.sign()). If any unexpected error occurs (e.g., failed database connection or invalid JWT signing), it could lead to the entire server crashing, preventing it from handling any further requests.
Proposed Solution

Wrap the asynchronous operations in try-catch blocks to ensure proper error handling. This will prevent the server from crashing and provide better feedback for users in case of an error.
Example:

In the signin route:

//javascript

router.post('/signin', async (req, res) => {
    try {
        const body = req.body;
        const parsedData = SigninSchema.safeParse(body);
        // Further logic...
    } catch (error) {
        res.status(500).json({ message: 'Internal server error' });
    }
});

Benefits

    Improved Stability: The server will no longer crash due to unhandled errors.
    Better Error Feedback: Users will receive clearer error messages instead of experiencing a service outage.

Could you kindly assign this issue to me, so I can work on it and implement the changes? Also, if possible, could you add the Hacktoberfest label to this issue?

Thank you for considering this! I look forward to contributing

**Comment by Kuldeepagrahari** [comment]
Hello [mesalm](https://github.com/mesalm),
please assign this issue , I can handle it as i have good experience of backend especiall MERN stack
