### ISSUE TITLE
Integrate Branding

### ISSUE THREAD

**Issue by Shivg2901** [Shivg2901/zapier-prototype#2]
Integrate the new Logo and Brand name in the website and no mention of zapier should remain

**Comment by mayank-0789** [comment]
Hey @Shivg2901  please assign this issue to me

**Comment by Shivg2901** [comment]
@mayank-0789 
assigned
Feel free to be creative

**Comment by Shivg2901** [comment]
@mayank-0789 
any update?

**Comment by mayank-0789** [comment]
working on it

**Comment by Shivg2901** [comment]
@mayank-0789  
What's the progress

**Comment by yashitz07** [comment]
Hey @Shivg2901 I would like to work on this task. Can you assign me this.
