### ISSUE TITLE
Handle auth errors

### ISSUE THREAD

**Issue by Shivg2901** [Shivg2901/zapier-prototype#3]
Currently on signing up if an account with the same email exists, the error is'nt handled
Similarly on logging in if account does'nt exist, it simple shows axios error
Find code for the same in /Users/shivanshgupta/Desktop/projects/zapier/primary-backend/src/router/user.ts
<img width="1470" alt="Screenshot 2024-10-09 at 2 29 13 PM" src="https://github.com/user-attachments/assets/04206641-8a5f-4f28-b8a8-3a09595d2c30">
<img width="1470" alt="Screenshot 2024-10-09 at 2 29 54 PM" src="https://github.com/user-attachments/assets/6100df1e-ad23-42b0-a518-143ef733bf1c">

**Comment by swymbnsl** [comment]
Hey @Shivg2901 . I would like to solve this issue, kindly assign it to me

**Comment by Shivg2901** [comment]
@swymbnsl 
Feel free to be creative
Either improve the existing code or you can also integrate authjs or some external auth provider.
We are flexible with that
